modLoader="javafml"
loaderVersion="${forgeloaderversion}"
license="${license}"
issueTrackerURL="${issues}"

[[mods]]
modId="cci_map_palette"
version="${version}"
displayName="CCI Map Palette"
description='''
${description}
'''
authors="Spinyowl"
displayURL="${homepage}"
logoFile="assets/cci_map_palette/icon.png"

[[dependencies.cci_map_palette]]
modId="forge"
mandatory=true
versionRange="${forgeversionrange}"
ordering="NONE"
side="BOTH"

[[dependencies.cci_map_palette]]
modId="minecraft"
mandatory=true
versionRange="${mcversion}"
ordering="NONE"
side="BOTH"

[[dependencies.cci_map_palette]]
modId="architectury"
mandatory=true
versionRange="[${archversion},)"
ordering="NONE"
side="BOTH"

[[dependencies.cci_map_palette]]
modId="ftbchunks"
mandatory=true
versionRange="${ftbchunksversionrange}"
ordering="NONE"
side="CLIENT"
