org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

org.gradle.warning.mode=all

# Mod
mod_id=cci_map_palette
archives_base_name=cci-map-palette
readable_name=CCI Map Palette
maven_group=com.spinyowl
mod_author=Spinyowl
mod_license=MIT
mod_description=Client-side runtime color overrides for FTB Chunks minimaps, with automatic texture-aware mapping for selected mod namespaces.
mod_homepage_url=https://github.com/Spinyowl/cci-map-palette
mod_sources_url=https://github.com/Spinyowl/cci-map-palette
mod_issues_url=https://github.com/Spinyowl/cci-map-palette/issues

mod_version=0.1.0
minecraft_version=1.20.1

# Publishing
curseforge_project_id=
curseforge_release_type=beta
curseforge_changelog_file=CHANGELOG.md

# Deps
architectury_version=9.1.12
fabric_loader_version=0.14.21
fabric_api_version=0.83.1+1.20.1
fabric_api_version_range=>=0.83.1+1.20.1

forge_version=47.1.47
forge_version_range=[47.1.0,48.0.0)
forge_loader_version=47

ftb_chunks_version=2001.3.6
ftb_chunks_version_range=[2001.3.6,)
ftb_library_version=2001.2.9
