pluginManagement {
	resolutionStrategy {
		eachPlugin {
			if (requested.id.id == "architectury-plugin") {
				useModule("me.shedaniel:architectury-plugin:${requested.version}")
			}
		}
	}

	repositories {
		maven { url = uri("https://maven.creeperhost.net/") }
		maven { url = uri("https://maven.shedaniel.me/") }
		maven {
			url = uri("https://maven.architectury.dev/")
			metadataSources {
				mavenPom()
				artifact()
				ignoreGradleMetadataRedirection()
			}
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

include "common", "fabric", "forge"

rootProject.name = 'cci-map-palette'
